name: Platform Tests
on: [push, pull_request]

jobs:
  platform_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.13.x, 1.16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: WillAbides/setup-go-faster@v1.5.0
      id: setup-go-faster
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build ./cmd/goinfo

    - name: Test
      run: go test -race ./...
