name: Static Analysis
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: WillAbides/setup-go-faster@v1.6.0
      with:
        go-version: '1.16.x'     

    - name: Get dependencies
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        go install golang.org/x/lint/golint@latest
        go install honnef.co/go/tools/cmd/staticcheck@v0.2.0

    - name: Vet
      run: go vet -tags ci ./...

    - name: Goimports
      run: test -z $(goimports -e -d . | tee /dev/stderr)

    - name: Gocyclo
      run: gocyclo -over 30 .

    - name: Golint
      run: golint -set_exit_status $(go list -tags ci ./...)

    - name: Staticcheck
      run: staticcheck -go 1.12 ./...
